# #arquivo de configuração
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: vendas-configmap
#   namespace: crm
#   annotations:
#     descriptions: map de variaveis de ambiente do projeto
# data:
#   ConcGCThreads: '10'
#   ParallelGCThreads: '10'
#   keycloak_lnk: keycloak.makesystem.com.br
#   keycloak_svc: keycloak.services.svc.cluster.local
#   namespace: production
#   portal_ip: portal.makesystem.com.br
#   portal_lnk: portal
#   portal_svc: portal-svc.portal.svc.cluster.local
#   services: services
#   servicos_lnk: services
#   servicos_svc: gateway-service-svc.services.svc.cluster.local
# ---  
# #Serviço de rede para direcionamento ao webcrm
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     run: vendas-webcrm    
#   name: vendas-webcrm-svc
#   namespace: crm
# spec:
#   ports:
#   - port: 443
#     name: https
#     protocol: TCP
#     targetPort: 8181
#   - port: 4848
#     name: admin
#     protocol: TCP
#     targetPort: 4848
#   - port: 8686
#     name: console
#     protocol: TCP
#     targetPort: 8686   
#   - port: 80
#     name: http
#     protocol: TCP
#     targetPort: 8080  
#   selector:
#     run: vendas-webcrm
#   sessionAffinity: None
#   type: ClusterIP
# ---
# #Serviço de rede para direcionamento ao robust
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     run: vendas-robust
#   name: vendas-svc
#   namespace: crm
# spec:
#   ports:
#   - port: 443
#     name: https
#     protocol: TCP
#     targetPort: 8181
#   - port: 4848
#     name: admin
#     protocol: TCP
#     targetPort: 4848
#   - port: 8686
#     name: console
#     protocol: TCP
#     targetPort: 8686   
#   - port: 80
#     name: http
#     protocol: TCP
#     targetPort: 8080  
#   selector:
#     run: vendas-robust
#   sessionAffinity: None
#   type: ClusterIP

# ---

# #Ingress para o dominio registrado separando os acessos para o serviço de webcrm e robust
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/proxy-body-size: "0"
#     nginx.ingress.kubernetes.io/proxy-read-timeout: "21600"
#     nginx.ingress.kubernetes.io/proxy-send-timeout: "21600"
#     nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
#     nginx.ingress.kubernetes.io/send-timeout: "3600"
#     nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
#     cert-manager.io/cluster-issuer: letsencrypt
#   name: vendas-ingress
#   namespace: crm
# spec:
#   rules:
#     - host: vendas.makesystem.com.br
#       http:
#         paths:
#           - backend:
#               service:
#                 name: vendas-webcrm-svc              
#                 port:
#                   number: 443
#             pathType: Prefix      
#             path: /
#           - backend:
#               service:
#                 name: vendas-svc              
#                 port:
#                   number: 443
#             pathType: Prefix      
#             path: /robust

#   tls:
#       - hosts:
#           - vendas.makesystem.com.br
#         secretName: tls-vendas
# #         #secretName: tls-secret2
# ---
#deploy somente do webcrm
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: crm
  name: crm06
  namespace: crm
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: crm06
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: crm06
    spec:
      hostname: crm06
      containers:
      #container do CRM
      - image:  makesystemdockerhub.azurecr.io/payara-crm:1.11.93.4
        imagePullPolicy: Always
        name: crm06
        env:
          - name: TZ
            value: America/Sao_Paulo        
          - name: services
            valueFrom:
              configMapKeyRef:
                name: crm06-configmap
                key: services              
          - name: portal_svc
            valueFrom:
              configMapKeyRef:
                name: vendas-configmap
                key: portal_svc
          - name: keycloak_svc
            valueFrom:
              configMapKeyRef:
                name: crm06-configmap
                key: keycloak_svc                
          - name: servicos_svc
            valueFrom:
              configMapKeyRef:
                name: crm06-configmap
                key: servicos_svc
          - name: servicos_lnk
            valueFrom:
              configMapKeyRef:
                name: crm06-configmap
                key: servicos_lnk
          - name: portal_lnk
            valueFrom:
              configMapKeyRef:
                name: crm06-configmap
                key: portal_lnk
          - name: keycloak_lnk
            valueFrom:
              configMapKeyRef:
                name: crm06-configmap
                key: keycloak_lnk                
          - name: namespace
            valueFrom:
              configMapKeyRef:
                name: crm06-configmap
                key: namespace
          - name: portal_ip
            valueFrom:
              configMapKeyRef:
                name: crm06-configmap
                key: portal_ip                
          - name: ConcGCThreads
            valueFrom:
              configMapKeyRef:
                name: crm06-configmap
                key: ConcGCThreads                
          - name: ParallelGCThreads
            valueFrom:
              configMapKeyRef:
                name: crm06-configmap
                key: ParallelGCThreads
        volumeMounts:         
        - name: webcrm-docroot
          mountPath: /opt/payara/appserver/glassfish/domains/domain1/docroot
        resources: 
          limits:
            memory: "2Gi"
            cpu: "2"
          requests:
            memory: 56Mi
            cpu: 100m        
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes: 
      - name: webcrm-docroot
        persistentVolumeClaim:
          claimName: crm-docroot-dir                   
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
      - name: crm06-secret      
      nodeSelector:
        kubernetes.io/hostname: aks-crm-18775914-vmss00000b
# ---
#deploy somente do robust
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     run: vendas-robust
#   name: vendas-robust
#   namespace: crm
# spec:
#   progressDeadlineSeconds: 600
#   replicas: 1
#   revisionHistoryLimit: 10
#   selector:
#     matchLabels:
#       run: vendas-robust
#   strategy:
#     rollingUpdate:
#       maxSurge: 1
#       maxUnavailable: 1
#     type: RollingUpdate
#   template:
#     metadata:
#       labels:
#         run: vendas-robust
#     spec:
#       hostname: vendas-robust
#       containers:
#       - image: makesystemdockerhub.azurecr.io/payara-crm:1.11.94.0
#         imagePullPolicy: Always
#         name: vendas-robust
#         env:
#           - name: TZ
#             value: America/Sao_Paulo        
#           - name: services
#             valueFrom:
#               configMapKeyRef:
#                 name: vendas-configmap
#                 key: services              
#           - name: portal_svc
#             valueFrom:
#               configMapKeyRef:
#                 name: vendas-configmap
#                 key: portal_svc
#           - name: keycloak_svc
#             valueFrom:
#               configMapKeyRef:
#                 name: vendas-configmap
#                 key: keycloak_svc                
#           - name: servicos_svc
#             valueFrom:
#               configMapKeyRef:
#                 name: vendas-configmap
#                 key: servicos_svc
#           - name: servicos_lnk
#             valueFrom:
#               configMapKeyRef:
#                 name: vendas-configmap
#                 key: servicos_lnk
#           - name: portal_lnk
#             valueFrom:
#               configMapKeyRef:
#                 name: vendas-configmap
#                 key: portal_lnk
#           - name: keycloak_lnk
#             valueFrom:
#               configMapKeyRef:
#                 name: vendas-configmap
#                 key: keycloak_lnk                
#           - name: namespace
#             valueFrom:
#               configMapKeyRef:
#                 name: vendas-configmap
#                 key: namespace
#           - name: portal_ip
#             valueFrom:
#               configMapKeyRef:
#                 name: vendas-configmap
#                 key: portal_ip                
#           - name: ConcGCThreads
#             valueFrom:
#               configMapKeyRef:
#                 name: vendas-configmap
#                 key: ConcGCThreads                
#           - name: ParallelGCThreads
#             valueFrom:
#               configMapKeyRef:
#                 name: vendas-configmap
#                 key: ParallelGCThreads
#         volumeMounts:         
#         - name: webcrm-docroot
#           mountPath: /opt/payara/appserver/glassfish/domains/domain1/docroot
#         resources: 
#           limits:
#             memory: "2Gi"
#             cpu: "2"
#           requests:
#             memory: 56Mi
#             cpu: 100m        
#         terminationMessagePath: /dev/termination-log
#         terminationMessagePolicy: File
#       volumes: 
#       - name: webcrm-docroot
#         persistentVolumeClaim:
#           claimName: crm-docroot-dir                   
#       dnsPolicy: ClusterFirst
#       restartPolicy: Always
#       schedulerName: default-scheduler
#       securityContext: {}
#       terminationGracePeriodSeconds: 30
#       imagePullSecrets:
#       - name: acr-secret      
#       nodeSelector:
#         kubernetes.io/hostname: aks-vipbr-10270306-vmss000000
