version: "3.7"

networks:
  base_sip_kong:
    external: false

volumes:
  postgres_data:
    driver: local
  

services:
  kong-database:
    image: postgres:9.5
    deploy:
      restart_policy:
        condition: any
    networks:
      - base_sip_kong
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migration-bootstrap:
    image: claudioed/kong-fc
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - base_sip_kong
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
    command: kong migrations bootstrap    

  kong-migration-up:
    image: claudioed/kong-fc
    networks:
      - base_sip_kong
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
    command: kong migrations up

  kong:
    container_name: kong_sip
    image: claudioed/kong-fc
    networks:
      - base_sip_kong
    deploy:
      restart_policy:
        condition: any
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8181, 0.0.0.0:8443 ssl http2
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_REAL_IP_RECURSIVE=on
      - KONG_NGINX_HTTP_RESOLVER=8.8.8.8
      - KONG_PLUGINS=bundled
    ports:
      - "80:8000"
      #- "443:8443"
      - "8001:8001"
    healthcheck:
      test: ["CMD", "wget", "-O-", "http://kong:8001/status"]
      interval: 5s
      retries: 10
    restart: on-failure

  base-sip:
    # container_name: basesip
    image: agnerft/ngnx-com-json-server:1.4
    networks:
      - base_sip_kong
    volumes:
      - teste
    # depends_on:
    #     - kong-database 
    deploy:
        restart_policy:
          condition: on-failure
    ports:
      - "8080:8080"
      - "443:8443"
      

  konga:
    image: pantsel/konga
    networks:
      - base_sip_kong
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - kong-database
    environment:
      NODE_ENV: development
    ports:
      - "1337:1337"

  nginx1:
    image: nginxdemos/hello
    
    networks:
      - base_sip_kong
    ports:
    - "8081:80"
    #- "443:9443"
  nginx2:
    image: nginxdemos/hello
    
    networks:
      - base_sip_kong
    ports:
    - "8082:80"
    #- "443:9443"

  nginx3:
    image: nginxdemos/hello
    
    networks:
      - base_sip_kong
    ports:
    - "8083:80"
    #- "443:9443"