apiVersion: v1
kind: Service
metadata:
  name: kong-database
  namespace: kong
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: kong-database

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-database
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-database
  template:
    metadata:
      labels:
        app: kong-database
    spec:
      containers:
        - name: postgres
          image: postgres:9.6
          env:
            - name: POSTGRES_USER
              value: kong
            - name: POSTGRES_DB
              value: kong
            - name: POSTGRES_PASSWORD
              value: kong
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - kong
            initialDelaySeconds: 5
            periodSeconds: 10

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-migration
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-migration
  template:
    metadata:
      labels:
        app: kong-migration
    spec:
      containers:
        - name: kong-fc
          image: kong:1.5
          command: ["kong", "migrations", "bootstrap"]
          env:
            - name: KONG_PG_HOST
              value: kong-database
            - name: KONG_PG_PASSWORD
              value: kong
          # restartPolicy: OnFailure
      # links:
      #   - kong-database
      # dependsOn:
      #   - kong-database


# 20.231.117.164



# version: "3"

# networks:
#  kong-net:
#   driver: bridge

# services:

#   #######################################
#   # Postgres: The database used by Kong
#   #######################################
#   kong-database:
#     image: postgres:9.6
#     restart: always
#     networks:
#       - kong-net
#     environment:
#       POSTGRES_USER: kong
#       POSTGRES_DB: kong
#       POSTGRES_PASSWORD: kong
#     ports:
#       - "5432:5432"
#     healthcheck:
#       test: ["CMD", "pg_isready", "-U", "kong"]
#       interval: 5s
#       timeout: 5s
#       retries: 5

#   #######################################
#   # Kong database migration
#   #######################################
#   kong-migration:
#     image: kong:1.5
#     command: "kong migrations bootstrap"
#     networks:
#       - kong-net
#     restart: on-failure
#     environment:
#       KONG_PG_HOST: kong-database
#       KONG_PG_PASSWORD: kong
#     links:
#       - kong-database
#     depends_on:
#       - kong-database

#   #######################################
#   # Kong: The API Gateway
#   #######################################
#   kong:
#     image: kong:1.5
#     restart: always
#     networks:
#       - kong-net
#     environment:
#       KONG_PG_HOST: kong-database
#       KONG_PG_PASSWORD: kong
#       KONG_PROXY_LISTEN: 0.0.0.0:8000
#       KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
#       KONG_ADMIN_LISTEN: 0.0.0.0:8001
#     depends_on:
#       - kong-database
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://kong:8001"]
#       interval: 5s
#       timeout: 2s
#       retries: 15
#     ports:
#       - 8001:8001
#       - 8000:8000


