apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: dev01
  name: dev01
  namespace: crm
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: dev01
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: dev01
    spec:
      hostname: dev01
      containers:
      - image: makesystemdockerhub.azurecr.io/payara-crm:1.11.91.6b
        imagePullPolicy: Always
        name: dev01
        env:
          - name: TZ
            value: America/Sao_Paulo        
          - name: services
            valueFrom:
              configMapKeyRef:
                name: dev01-configmap
                key: services              
          - name: portal_svc
            valueFrom:
              configMapKeyRef:
                name: dev01-configmap
                key: portal_svc
          - name: keycloak_svc
            valueFrom:
              configMapKeyRef:
                name: dev01-configmap
                key: keycloak_svc                
          - name: servicos_svc
            valueFrom:
              configMapKeyRef:
                name: dev01-configmap
                key: servicos_svc
          - name: servicos_lnk
            valueFrom:
              configMapKeyRef:
                name: dev01-configmap
                key: servicos_lnk
          - name: portal_lnk
            valueFrom:
              configMapKeyRef:
                name: dev01-configmap
                key: portal_lnk
          - name: keycloak_lnk
            valueFrom:
              configMapKeyRef:
                name: dev01-configmap
                key: keycloak_lnk                
          - name: namespace
            valueFrom:
              configMapKeyRef:
                name: dev01-configmap
                key: namespace
          - name: portal_ip
            valueFrom:
              configMapKeyRef:
                name: dev01-configmap
                key: portal_ip
        volumeMounts:         
        - name: webcrm-docroot
          mountPath: /opt/payara/appserver/glassfish/domains/domain1/docroot
        resources: 
          limits:
            memory: "6Gi"
            cpu: "2"
          requests:
            memory: "512Mi"
            cpu: "100m"        
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes: 
      - name: webcrm-docroot
        persistentVolumeClaim:
          claimName: crm-docroot-dir                   
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
      - name: acr-secret      
      nodeSelector:
        kubernetes.io/hostname: aks-webcrm-11037662-vmss000003
